/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FinanzRouteImport } from './routes/finanz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupabaseSetupRouteImport } from './routes/supabase-setup'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as DashboardContractorRouteRouteImport } from './routes/_dashboard/contractor/route'
import { Route as DashboardDevRouteImport } from './routes/_dashboard/dev'
import { Route as DashboardHomeownerRouteRouteImport } from './routes/_dashboard/homeowner/route'
import { Route as DashboardMessagesRouteImport } from './routes/_dashboard/messages'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard/notifications'
import { Route as DashboardSecurityRouteImport } from './routes/_dashboard/security'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTranscribeStreamRouteImport } from './routes/api/transcribe-stream'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'
import { Route as PProfileIdRouteImport } from './routes/p.$profileId'
import { Route as TradesSpecialtyRouteImport } from './routes/trades.$specialty'
import { Route as DashboardContractorIndexRouteImport } from './routes/_dashboard/contractor/index'
import { Route as DashboardContractorCalendarRouteImport } from './routes/_dashboard/contractor/calendar'
import { Route as DashboardContractorDailyLogRouteImport } from './routes/_dashboard/contractor/daily-log'
import { Route as DashboardContractorNetworkRouteImport } from './routes/_dashboard/contractor/network'
import { Route as DashboardContractorPerformanceRouteImport } from './routes/_dashboard/contractor/performance'
import { Route as DashboardContractorProfileRouteImport } from './routes/_dashboard/contractor/profile'
import { Route as DashboardContractorReportsRouteImport } from './routes/_dashboard/contractor/reports'
import { Route as DashboardContractorStaffHoursRouteImport } from './routes/_dashboard/contractor/staff-hours'
import { Route as DashboardContractorTeamRouteImport } from './routes/_dashboard/contractor/team'
import { Route as DashboardHomeownerIndexRouteImport } from './routes/_dashboard/homeowner/index'
import { Route as DashboardHomeownerBrowseRouteImport } from './routes/_dashboard/homeowner/browse'
import { Route as DashboardHomeownerPropertiesRouteImport } from './routes/_dashboard/homeowner/properties'
import { Route as DashboardContractorJobsActiveRouteImport } from './routes/_dashboard/contractor/jobs.active'
import { Route as DashboardContractorJobsQuotesRouteImport } from './routes/_dashboard/contractor/jobs.quotes'
import { Route as DashboardContractorNetworkIndexRouteImport } from './routes/_dashboard/contractor/network.index'
import { Route as DashboardContractorNetworkThreadIdRouteImport } from './routes/_dashboard/contractor/network.$threadId'
import { Route as DashboardContractorTeamLocationsRouteImport } from './routes/_dashboard/contractor/team.locations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzRoute = FinanzRouteImport.update({
  id: '/finanz',
  path: '/finanz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupabaseSetupRoute = SupabaseSetupRouteImport.update({
  id: '/supabase-setup',
  path: '/supabase-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardContractorRouteRoute =
  DashboardContractorRouteRouteImport.update({
    id: '/contractor',
    path: '/contractor',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDevRoute = DashboardDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeownerRouteRoute = DashboardHomeownerRouteRouteImport.update({
  id: '/homeowner',
  path: '/homeowner',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeStreamRoute = ApiTranscribeStreamRouteImport.update({
  id: '/api/transcribe-stream',
  path: '/api/transcribe-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PProfileIdRoute = PProfileIdRouteImport.update({
  id: '/p/$profileId',
  path: '/p/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesSpecialtyRoute = TradesSpecialtyRouteImport.update({
  id: '/trades/$specialty',
  path: '/trades/$specialty',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContractorIndexRoute =
  DashboardContractorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorCalendarRoute =
  DashboardContractorCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorDailyLogRoute =
  DashboardContractorDailyLogRouteImport.update({
    id: '/daily-log',
    path: '/daily-log',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorNetworkRoute =
  DashboardContractorNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorPerformanceRoute =
  DashboardContractorPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorProfileRoute =
  DashboardContractorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorReportsRoute =
  DashboardContractorReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorStaffHoursRoute =
  DashboardContractorStaffHoursRouteImport.update({
    id: '/staff-hours',
    path: '/staff-hours',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorTeamRoute = DashboardContractorTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardContractorRouteRoute,
} as any)
const DashboardHomeownerIndexRoute = DashboardHomeownerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardHomeownerRouteRoute,
} as any)
const DashboardHomeownerBrowseRoute =
  DashboardHomeownerBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => DashboardHomeownerRouteRoute,
  } as any)
const DashboardHomeownerPropertiesRoute =
  DashboardHomeownerPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => DashboardHomeownerRouteRoute,
  } as any)
const DashboardContractorJobsActiveRoute =
  DashboardContractorJobsActiveRouteImport.update({
    id: '/jobs/active',
    path: '/jobs/active',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorJobsQuotesRoute =
  DashboardContractorJobsQuotesRouteImport.update({
    id: '/jobs/quotes',
    path: '/jobs/quotes',
    getParentRoute: () => DashboardContractorRouteRoute,
  } as any)
const DashboardContractorNetworkIndexRoute =
  DashboardContractorNetworkIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardContractorNetworkRoute,
  } as any)
const DashboardContractorNetworkThreadIdRoute =
  DashboardContractorNetworkThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => DashboardContractorNetworkRoute,
  } as any)
const DashboardContractorTeamLocationsRoute =
  DashboardContractorTeamLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => DashboardContractorTeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/finanz': typeof FinanzRoute
  '/impressum': typeof ImpressumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-setup': typeof SupabaseSetupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/contractor': typeof DashboardContractorRouteRouteWithChildren
  '/homeowner': typeof DashboardHomeownerRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dev': typeof DashboardDevRoute
  '/messages': typeof DashboardMessagesRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/security': typeof DashboardSecurityRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-stream': typeof ApiTranscribeStreamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/p/$profileId': typeof PProfileIdRoute
  '/trades/$specialty': typeof TradesSpecialtyRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/contractor/calendar': typeof DashboardContractorCalendarRoute
  '/contractor/daily-log': typeof DashboardContractorDailyLogRoute
  '/contractor/network': typeof DashboardContractorNetworkRouteWithChildren
  '/contractor/performance': typeof DashboardContractorPerformanceRoute
  '/contractor/profile': typeof DashboardContractorProfileRoute
  '/contractor/reports': typeof DashboardContractorReportsRoute
  '/contractor/staff-hours': typeof DashboardContractorStaffHoursRoute
  '/contractor/team': typeof DashboardContractorTeamRouteWithChildren
  '/homeowner/browse': typeof DashboardHomeownerBrowseRoute
  '/homeowner/properties': typeof DashboardHomeownerPropertiesRoute
  '/contractor/': typeof DashboardContractorIndexRoute
  '/homeowner/': typeof DashboardHomeownerIndexRoute
  '/contractor/jobs/active': typeof DashboardContractorJobsActiveRoute
  '/contractor/jobs/quotes': typeof DashboardContractorJobsQuotesRoute
  '/contractor/network/$threadId': typeof DashboardContractorNetworkThreadIdRoute
  '/contractor/team/locations': typeof DashboardContractorTeamLocationsRoute
  '/contractor/network/': typeof DashboardContractorNetworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/finanz': typeof FinanzRoute
  '/impressum': typeof ImpressumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-setup': typeof SupabaseSetupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dev': typeof DashboardDevRoute
  '/messages': typeof DashboardMessagesRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/security': typeof DashboardSecurityRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-stream': typeof ApiTranscribeStreamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/p/$profileId': typeof PProfileIdRoute
  '/trades/$specialty': typeof TradesSpecialtyRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/contractor/calendar': typeof DashboardContractorCalendarRoute
  '/contractor/daily-log': typeof DashboardContractorDailyLogRoute
  '/contractor/performance': typeof DashboardContractorPerformanceRoute
  '/contractor/profile': typeof DashboardContractorProfileRoute
  '/contractor/reports': typeof DashboardContractorReportsRoute
  '/contractor/staff-hours': typeof DashboardContractorStaffHoursRoute
  '/contractor/team': typeof DashboardContractorTeamRouteWithChildren
  '/homeowner/browse': typeof DashboardHomeownerBrowseRoute
  '/homeowner/properties': typeof DashboardHomeownerPropertiesRoute
  '/contractor': typeof DashboardContractorIndexRoute
  '/homeowner': typeof DashboardHomeownerIndexRoute
  '/contractor/jobs/active': typeof DashboardContractorJobsActiveRoute
  '/contractor/jobs/quotes': typeof DashboardContractorJobsQuotesRoute
  '/contractor/network/$threadId': typeof DashboardContractorNetworkThreadIdRoute
  '/contractor/team/locations': typeof DashboardContractorTeamLocationsRoute
  '/contractor/network': typeof DashboardContractorNetworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/finanz': typeof FinanzRoute
  '/impressum': typeof ImpressumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supabase-setup': typeof SupabaseSetupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_dashboard/contractor': typeof DashboardContractorRouteRouteWithChildren
  '/_dashboard/homeowner': typeof DashboardHomeownerRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/dev': typeof DashboardDevRoute
  '/_dashboard/messages': typeof DashboardMessagesRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/security': typeof DashboardSecurityRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/transcribe-stream': typeof ApiTranscribeStreamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/p/$profileId': typeof PProfileIdRoute
  '/trades/$specialty': typeof TradesSpecialtyRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_dashboard/contractor/calendar': typeof DashboardContractorCalendarRoute
  '/_dashboard/contractor/daily-log': typeof DashboardContractorDailyLogRoute
  '/_dashboard/contractor/network': typeof DashboardContractorNetworkRouteWithChildren
  '/_dashboard/contractor/performance': typeof DashboardContractorPerformanceRoute
  '/_dashboard/contractor/profile': typeof DashboardContractorProfileRoute
  '/_dashboard/contractor/reports': typeof DashboardContractorReportsRoute
  '/_dashboard/contractor/staff-hours': typeof DashboardContractorStaffHoursRoute
  '/_dashboard/contractor/team': typeof DashboardContractorTeamRouteWithChildren
  '/_dashboard/homeowner/browse': typeof DashboardHomeownerBrowseRoute
  '/_dashboard/homeowner/properties': typeof DashboardHomeownerPropertiesRoute
  '/_dashboard/contractor/': typeof DashboardContractorIndexRoute
  '/_dashboard/homeowner/': typeof DashboardHomeownerIndexRoute
  '/_dashboard/contractor/jobs/active': typeof DashboardContractorJobsActiveRoute
  '/_dashboard/contractor/jobs/quotes': typeof DashboardContractorJobsQuotesRoute
  '/_dashboard/contractor/network/$threadId': typeof DashboardContractorNetworkThreadIdRoute
  '/_dashboard/contractor/team/locations': typeof DashboardContractorTeamLocationsRoute
  '/_dashboard/contractor/network/': typeof DashboardContractorNetworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/finanz'
    | '/impressum'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/supabase-setup'
    | '/terms-of-service'
    | '/contractor'
    | '/homeowner'
    | '/login'
    | '/signup'
    | '/dev'
    | '/messages'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/api/health'
    | '/api/transcribe-stream'
    | '/auth/callback'
    | '/onboarding/profile'
    | '/p/$profileId'
    | '/trades/$specialty'
    | '/onboarding/'
    | '/contractor/calendar'
    | '/contractor/daily-log'
    | '/contractor/network'
    | '/contractor/performance'
    | '/contractor/profile'
    | '/contractor/reports'
    | '/contractor/staff-hours'
    | '/contractor/team'
    | '/homeowner/browse'
    | '/homeowner/properties'
    | '/contractor/'
    | '/homeowner/'
    | '/contractor/jobs/active'
    | '/contractor/jobs/quotes'
    | '/contractor/network/$threadId'
    | '/contractor/team/locations'
    | '/contractor/network/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/finanz'
    | '/impressum'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/supabase-setup'
    | '/terms-of-service'
    | '/login'
    | '/signup'
    | '/dev'
    | '/messages'
    | '/notifications'
    | '/security'
    | '/settings'
    | '/api/health'
    | '/api/transcribe-stream'
    | '/auth/callback'
    | '/onboarding/profile'
    | '/p/$profileId'
    | '/trades/$specialty'
    | '/onboarding'
    | '/contractor/calendar'
    | '/contractor/daily-log'
    | '/contractor/performance'
    | '/contractor/profile'
    | '/contractor/reports'
    | '/contractor/staff-hours'
    | '/contractor/team'
    | '/homeowner/browse'
    | '/homeowner/properties'
    | '/contractor'
    | '/homeowner'
    | '/contractor/jobs/active'
    | '/contractor/jobs/quotes'
    | '/contractor/network/$threadId'
    | '/contractor/team/locations'
    | '/contractor/network'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/datenschutz'
    | '/finanz'
    | '/impressum'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/supabase-setup'
    | '/terms-of-service'
    | '/_dashboard/contractor'
    | '/_dashboard/homeowner'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/dev'
    | '/_dashboard/messages'
    | '/_dashboard/notifications'
    | '/_dashboard/security'
    | '/_dashboard/settings'
    | '/api/health'
    | '/api/transcribe-stream'
    | '/auth/callback'
    | '/onboarding/profile'
    | '/p/$profileId'
    | '/trades/$specialty'
    | '/onboarding/'
    | '/_dashboard/contractor/calendar'
    | '/_dashboard/contractor/daily-log'
    | '/_dashboard/contractor/network'
    | '/_dashboard/contractor/performance'
    | '/_dashboard/contractor/profile'
    | '/_dashboard/contractor/reports'
    | '/_dashboard/contractor/staff-hours'
    | '/_dashboard/contractor/team'
    | '/_dashboard/homeowner/browse'
    | '/_dashboard/homeowner/properties'
    | '/_dashboard/contractor/'
    | '/_dashboard/homeowner/'
    | '/_dashboard/contractor/jobs/active'
    | '/_dashboard/contractor/jobs/quotes'
    | '/_dashboard/contractor/network/$threadId'
    | '/_dashboard/contractor/team/locations'
    | '/_dashboard/contractor/network/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  FinanzRoute: typeof FinanzRoute
  ImpressumRoute: typeof ImpressumRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupabaseSetupRoute: typeof SupabaseSetupRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTranscribeStreamRoute: typeof ApiTranscribeStreamRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  PProfileIdRoute: typeof PProfileIdRoute
  TradesSpecialtyRoute: typeof TradesSpecialtyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanz': {
      id: '/finanz'
      path: '/finanz'
      fullPath: '/finanz'
      preLoaderRoute: typeof FinanzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supabase-setup': {
      id: '/supabase-setup'
      path: '/supabase-setup'
      fullPath: '/supabase-setup'
      preLoaderRoute: typeof SupabaseSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/contractor': {
      id: '/_dashboard/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof DashboardContractorRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dev': {
      id: '/_dashboard/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DashboardDevRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/homeowner': {
      id: '/_dashboard/homeowner'
      path: '/homeowner'
      fullPath: '/homeowner'
      preLoaderRoute: typeof DashboardHomeownerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/messages': {
      id: '/_dashboard/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/security': {
      id: '/_dashboard/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-stream': {
      id: '/api/transcribe-stream'
      path: '/api/transcribe-stream'
      fullPath: '/api/transcribe-stream'
      preLoaderRoute: typeof ApiTranscribeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$profileId': {
      id: '/p/$profileId'
      path: '/p/$profileId'
      fullPath: '/p/$profileId'
      preLoaderRoute: typeof PProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades/$specialty': {
      id: '/trades/$specialty'
      path: '/trades/$specialty'
      fullPath: '/trades/$specialty'
      preLoaderRoute: typeof TradesSpecialtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/contractor/': {
      id: '/_dashboard/contractor/'
      path: '/'
      fullPath: '/contractor/'
      preLoaderRoute: typeof DashboardContractorIndexRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/calendar': {
      id: '/_dashboard/contractor/calendar'
      path: '/calendar'
      fullPath: '/contractor/calendar'
      preLoaderRoute: typeof DashboardContractorCalendarRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/daily-log': {
      id: '/_dashboard/contractor/daily-log'
      path: '/daily-log'
      fullPath: '/contractor/daily-log'
      preLoaderRoute: typeof DashboardContractorDailyLogRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/network': {
      id: '/_dashboard/contractor/network'
      path: '/network'
      fullPath: '/contractor/network'
      preLoaderRoute: typeof DashboardContractorNetworkRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/performance': {
      id: '/_dashboard/contractor/performance'
      path: '/performance'
      fullPath: '/contractor/performance'
      preLoaderRoute: typeof DashboardContractorPerformanceRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/profile': {
      id: '/_dashboard/contractor/profile'
      path: '/profile'
      fullPath: '/contractor/profile'
      preLoaderRoute: typeof DashboardContractorProfileRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/reports': {
      id: '/_dashboard/contractor/reports'
      path: '/reports'
      fullPath: '/contractor/reports'
      preLoaderRoute: typeof DashboardContractorReportsRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/staff-hours': {
      id: '/_dashboard/contractor/staff-hours'
      path: '/staff-hours'
      fullPath: '/contractor/staff-hours'
      preLoaderRoute: typeof DashboardContractorStaffHoursRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/team': {
      id: '/_dashboard/contractor/team'
      path: '/team'
      fullPath: '/contractor/team'
      preLoaderRoute: typeof DashboardContractorTeamRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/homeowner/': {
      id: '/_dashboard/homeowner/'
      path: '/'
      fullPath: '/homeowner/'
      preLoaderRoute: typeof DashboardHomeownerIndexRouteImport
      parentRoute: typeof DashboardHomeownerRouteRoute
    }
    '/_dashboard/homeowner/browse': {
      id: '/_dashboard/homeowner/browse'
      path: '/browse'
      fullPath: '/homeowner/browse'
      preLoaderRoute: typeof DashboardHomeownerBrowseRouteImport
      parentRoute: typeof DashboardHomeownerRouteRoute
    }
    '/_dashboard/homeowner/properties': {
      id: '/_dashboard/homeowner/properties'
      path: '/properties'
      fullPath: '/homeowner/properties'
      preLoaderRoute: typeof DashboardHomeownerPropertiesRouteImport
      parentRoute: typeof DashboardHomeownerRouteRoute
    }
    '/_dashboard/contractor/jobs/active': {
      id: '/_dashboard/contractor/jobs/active'
      path: '/jobs/active'
      fullPath: '/contractor/jobs/active'
      preLoaderRoute: typeof DashboardContractorJobsActiveRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/jobs/quotes': {
      id: '/_dashboard/contractor/jobs/quotes'
      path: '/jobs/quotes'
      fullPath: '/contractor/jobs/quotes'
      preLoaderRoute: typeof DashboardContractorJobsQuotesRouteImport
      parentRoute: typeof DashboardContractorRouteRoute
    }
    '/_dashboard/contractor/network/': {
      id: '/_dashboard/contractor/network/'
      path: '/'
      fullPath: '/contractor/network/'
      preLoaderRoute: typeof DashboardContractorNetworkIndexRouteImport
      parentRoute: typeof DashboardContractorNetworkRoute
    }
    '/_dashboard/contractor/network/$threadId': {
      id: '/_dashboard/contractor/network/$threadId'
      path: '/$threadId'
      fullPath: '/contractor/network/$threadId'
      preLoaderRoute: typeof DashboardContractorNetworkThreadIdRouteImport
      parentRoute: typeof DashboardContractorNetworkRoute
    }
    '/_dashboard/contractor/team/locations': {
      id: '/_dashboard/contractor/team/locations'
      path: '/locations'
      fullPath: '/contractor/team/locations'
      preLoaderRoute: typeof DashboardContractorTeamLocationsRouteImport
      parentRoute: typeof DashboardContractorTeamRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardContractorNetworkRouteChildren {
  DashboardContractorNetworkThreadIdRoute: typeof DashboardContractorNetworkThreadIdRoute
  DashboardContractorNetworkIndexRoute: typeof DashboardContractorNetworkIndexRoute
}

const DashboardContractorNetworkRouteChildren: DashboardContractorNetworkRouteChildren =
  {
    DashboardContractorNetworkThreadIdRoute:
      DashboardContractorNetworkThreadIdRoute,
    DashboardContractorNetworkIndexRoute: DashboardContractorNetworkIndexRoute,
  }

const DashboardContractorNetworkRouteWithChildren =
  DashboardContractorNetworkRoute._addFileChildren(
    DashboardContractorNetworkRouteChildren,
  )

interface DashboardContractorTeamRouteChildren {
  DashboardContractorTeamLocationsRoute: typeof DashboardContractorTeamLocationsRoute
}

const DashboardContractorTeamRouteChildren: DashboardContractorTeamRouteChildren =
  {
    DashboardContractorTeamLocationsRoute:
      DashboardContractorTeamLocationsRoute,
  }

const DashboardContractorTeamRouteWithChildren =
  DashboardContractorTeamRoute._addFileChildren(
    DashboardContractorTeamRouteChildren,
  )

interface DashboardContractorRouteRouteChildren {
  DashboardContractorCalendarRoute: typeof DashboardContractorCalendarRoute
  DashboardContractorDailyLogRoute: typeof DashboardContractorDailyLogRoute
  DashboardContractorNetworkRoute: typeof DashboardContractorNetworkRouteWithChildren
  DashboardContractorPerformanceRoute: typeof DashboardContractorPerformanceRoute
  DashboardContractorProfileRoute: typeof DashboardContractorProfileRoute
  DashboardContractorReportsRoute: typeof DashboardContractorReportsRoute
  DashboardContractorStaffHoursRoute: typeof DashboardContractorStaffHoursRoute
  DashboardContractorTeamRoute: typeof DashboardContractorTeamRouteWithChildren
  DashboardContractorIndexRoute: typeof DashboardContractorIndexRoute
  DashboardContractorJobsActiveRoute: typeof DashboardContractorJobsActiveRoute
  DashboardContractorJobsQuotesRoute: typeof DashboardContractorJobsQuotesRoute
}

const DashboardContractorRouteRouteChildren: DashboardContractorRouteRouteChildren =
  {
    DashboardContractorCalendarRoute: DashboardContractorCalendarRoute,
    DashboardContractorDailyLogRoute: DashboardContractorDailyLogRoute,
    DashboardContractorNetworkRoute:
      DashboardContractorNetworkRouteWithChildren,
    DashboardContractorPerformanceRoute: DashboardContractorPerformanceRoute,
    DashboardContractorProfileRoute: DashboardContractorProfileRoute,
    DashboardContractorReportsRoute: DashboardContractorReportsRoute,
    DashboardContractorStaffHoursRoute: DashboardContractorStaffHoursRoute,
    DashboardContractorTeamRoute: DashboardContractorTeamRouteWithChildren,
    DashboardContractorIndexRoute: DashboardContractorIndexRoute,
    DashboardContractorJobsActiveRoute: DashboardContractorJobsActiveRoute,
    DashboardContractorJobsQuotesRoute: DashboardContractorJobsQuotesRoute,
  }

const DashboardContractorRouteRouteWithChildren =
  DashboardContractorRouteRoute._addFileChildren(
    DashboardContractorRouteRouteChildren,
  )

interface DashboardHomeownerRouteRouteChildren {
  DashboardHomeownerBrowseRoute: typeof DashboardHomeownerBrowseRoute
  DashboardHomeownerPropertiesRoute: typeof DashboardHomeownerPropertiesRoute
  DashboardHomeownerIndexRoute: typeof DashboardHomeownerIndexRoute
}

const DashboardHomeownerRouteRouteChildren: DashboardHomeownerRouteRouteChildren =
  {
    DashboardHomeownerBrowseRoute: DashboardHomeownerBrowseRoute,
    DashboardHomeownerPropertiesRoute: DashboardHomeownerPropertiesRoute,
    DashboardHomeownerIndexRoute: DashboardHomeownerIndexRoute,
  }

const DashboardHomeownerRouteRouteWithChildren =
  DashboardHomeownerRouteRoute._addFileChildren(
    DashboardHomeownerRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardContractorRouteRoute: typeof DashboardContractorRouteRouteWithChildren
  DashboardHomeownerRouteRoute: typeof DashboardHomeownerRouteRouteWithChildren
  DashboardDevRoute: typeof DashboardDevRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardContractorRouteRoute: DashboardContractorRouteRouteWithChildren,
  DashboardHomeownerRouteRoute: DashboardHomeownerRouteRouteWithChildren,
  DashboardDevRoute: DashboardDevRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  FinanzRoute: FinanzRoute,
  ImpressumRoute: ImpressumRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupabaseSetupRoute: SupabaseSetupRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTranscribeStreamRoute: ApiTranscribeStreamRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  PProfileIdRoute: PProfileIdRoute,
  TradesSpecialtyRoute: TradesSpecialtyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
